### ISSUE TITLE
Replace `viper` with alternative in `configvalidator` package

### ISSUE THREAD

**Issue by siddhant-deepsource** [DeepSourceCorp/cli#152]
We are using `viper` in `configvalidator` package for the `deepsource config validate` command to read the `.deepsource.toml` config which is to be validated.

Viper can be replaced here with other libraries which have a lower size footprint and are focused only on reading TOML files.

Files where `viper` is used:
- https://github.com/deepsourcelabs/cli/blob/master/configvalidator/config_validator.go
- https://github.com/deepsourcelabs/cli/blob/master/configvalidator/generic_config_validator.go

**Comment by PyAgni** [comment]
Can I work on this issue? 
viper can be replaced with [pelletier/go-toml](https://github.com/pelletier/go-toml). In fact, viper uses that internally for toml files. Open to discussing other alternatives as well.
