### ISSUE TITLE
Separate builds for CI binaries using build tags

### ISSUE THREAD

**Issue by siddhant-deepsource** [DeepSourceCorp/cli#165]
Since we are adding new commands to CLI, the size of the binary is constantly increasing. This reflects in the case when the users pull the CLI binary in their CI systems as the time to pull the binary increases. Thus, creating a separate binary on every release that will be served if the environment is a CI system is the need.

**Comment by burntcarrot** [comment]
Working on this.

**Comment by vishnu-deepsource** [comment]
The size of the package is still considerably small.  Does not make sense to add this complexity in the build.
