### ISSUE TITLE
Add --version

### ISSUE THREAD

**Issue by jayvdb** [DeepSourceCorp/cli#246]
`--version` is a cheap way to verify a binary is usable, and record in the logs which version was used, useful for detecting when a new release started causing a problem.

**Comment by jayvdb** [comment]
It appears there is a subcommand `version`.  I believe `--version` is the expected way to get the version. See https://github.com/taiki-e/install-action/issues/577

**Comment by jai-deepsource** [comment]
@jayvdb as you mentioned, you can use `deepsource version` which returns the currently installed version.
